### ISSUE TITLE
OR/AND operator must short-circuit on falsey condition

### ISSUE THREAD

**Issue by justsml** [elite-libs/rules-machine#38]

**Comment by mattcfox** [comment]
`AND` keyword in expression seems to evaluate to false every time, as well.

**Comment by chhatch** [comment]
@mattcfox I have encountered the same issue. In my notes from last week I have, "string AND isn't working", but I haven't been able to reproduce it this morning. For instance, this is working for me:
```js
const rules = [
    { if: "foo AND true", then: "bar = 1", else: "bar = 0" },
    { return: "bar" },
  ];
console.log(ruleFactory(rules)({ foo: true }));  // 1
```
Do you have an example you can provide?

**Comment by chhatch** [comment]
Draft pr started here: https://github.com/elite-libs/rules-machine/pull/40
