### ISSUE TITLE
Which package?

### ISSUE THREAD

**Issue by rogueturnip** [elite-libs/rules-machine#5]
Just a bit confused on packages.  When I go to NPM I see
rules-machine
@elite-libs/rules-machine
@rules-tools/rules-machine

Which is the preferred package?

Also getting this when I try to use the package
Cannot find module '/XXXX/rulesMachine/node_modules/@elite-libs/rules-machine/dist/main.js

When I check the package folder there is no /dist folder in there.  I'm just using the fish example to try it out right now.

**Comment by justsml** [comment]
Thanks @rogueturnip - I'm about to release a fixed bundle. (Within a day or 2.)

**Comment by HaishengLiang** [comment]
I am also confused. 
If you are the author of all three libraries, can you release a statement to help users make a choice?

**Comment by chhatch** [comment]
@HaishengLiang I recommend `@elite-libs/rules-machine`. It's the one I use. I don't know about the other packages.
