### ISSUE TITLE
dist is missing in package

### ISSUE THREAD

**Issue by joaomilho** [elite-libs/rules-machine#6]
After installing 1.0.1 TS says it can't find the types for the package. It seems the dist folder is not there.

<img width="1015" alt="Screenshot 2022-03-28 at 12 42 57" src="https://user-images.githubusercontent.com/308196/160381738-5db036ac-1f3f-4796-8ac7-f2420172d491.png">

**Comment by justsml** [comment]
Hi @joaomilho - new bundle coming in the next day or 2. Thanks!
